insert into Artist (idArtist, name, idGenre) values (1, 'Brown LLC', 2);
insert into Artist (idArtist, name, idGenre) values (2, 'Batz-Adams', 8);
insert into Artist (idArtist, name, idGenre) values (3, 'Hartmann Group', 5);
insert into Artist (idArtist, name, idGenre) values (4, 'Nolan, Ferry and Hahn', 4);
insert into Artist (idArtist, name, idGenre) values (5, 'Kirlin Group', 2);
insert into Artist (idArtist, name, idGenre) values (6, 'Kshlerin LLC', 3);
insert into Artist (idArtist, name, idGenre) values (7, 'Raynor-Lehner', 5);
insert into Artist (idArtist, name, idGenre) values (8, 'Pfeffer Inc', 8);
insert into Artist (idArtist, name, idGenre) values (9, 'Gorczany Group', 5);
insert into Artist (idArtist, name, idGenre) values (10, 'Thompson Inc', 8);
insert into Artist (idArtist, name, idGenre) values (11, 'Marvin, Ledner and O''Keefe', 1);
insert into Artist (idArtist, name, idGenre) values (12, 'Blick-Waelchi', 7);
insert into Artist (idArtist, name, idGenre) values (13, 'Bruen, Mertz and Langosh', 6);
insert into Artist (idArtist, name, idGenre) values (14, 'Kilback, Lockman and Toy', 1);
insert into Artist (idArtist, name, idGenre) values (15, 'Robel, Weissnat and Heathcote', 4);
insert into Artist (idArtist, name, idGenre) values (16, 'Anderson, Kunde and Gutkowski', 7);
insert into Artist (idArtist, name, idGenre) values (17, 'Schinner, Pacocha and Hansen', 3);
insert into Artist (idArtist, name, idGenre) values (18, 'Mann, Walsh and O''Connell', 7);
insert into Artist (idArtist, name, idGenre) values (19, 'Lockman-Schowalter', 3);
insert into Artist (idArtist, name, idGenre) values (20, 'Greenholt Inc', 6);
insert into Artist (idArtist, name, idGenre) values (21, 'Mante Inc', 2);
insert into Artist (idArtist, name, idGenre) values (22, 'Robel-Renner', 4);
insert into Artist (idArtist, name, idGenre) values (23, 'MacGyver Group', 6);
insert into Artist (idArtist, name, idGenre) values (24, 'Mertz-Hodkiewicz', 6);
insert into Artist (idArtist, name, idGenre) values (25, 'Nicolas, Wyman and Stanton', 1);
insert into Artist (idArtist, name, idGenre) values (26, 'Dooley, Torphy and Blanda', 2);
insert into Artist (idArtist, name, idGenre) values (27, 'Farrell-Robel', 8);
insert into Artist (idArtist, name, idGenre) values (28, 'Cormier Group', 1);
insert into Artist (idArtist, name, idGenre) values (29, 'King, Weimann and Schumm', 6);
insert into Artist (idArtist, name, idGenre) values (30, 'Hirthe, Rowe and Barton', 1);
insert into Artist (idArtist, name, idGenre) values (31, 'Hahn, Schroeder and Hoeger', 3);
insert into Artist (idArtist, name, idGenre) values (32, 'Swift, Lang and Hahn', 2);
insert into Artist (idArtist, name, idGenre) values (33, 'Pouros-Denesik', 8);
insert into Artist (idArtist, name, idGenre) values (34, 'Gusikowski-Treutel', 2);
insert into Artist (idArtist, name, idGenre) values (35, 'Bins LLC', 4);
insert into Artist (idArtist, name, idGenre) values (36, 'Auer Group', 2);
insert into Artist (idArtist, name, idGenre) values (37, 'Turcotte and Sons', 1);
insert into Artist (idArtist, name, idGenre) values (38, 'Pacocha-Willms', 7);
insert into Artist (idArtist, name, idGenre) values (39, 'Conroy-Mann', 4);
insert into Artist (idArtist, name, idGenre) values (40, 'Brekke, Cremin and Kunde', 5);
insert into Artist (idArtist, name, idGenre) values (41, 'Schamberger and Sons', 8);
insert into Artist (idArtist, name, idGenre) values (42, 'Langosh-Daniel', 3);
insert into Artist (idArtist, name, idGenre) values (43, 'Robel, Kassulke and Zulauf', 1);
insert into Artist (idArtist, name, idGenre) values (44, 'Herman-Mayert', 6);
insert into Artist (idArtist, name, idGenre) values (45, 'Swift, Abbott and Ullrich', 8);
insert into Artist (idArtist, name, idGenre) values (46, 'King, Hickle and Ondricka', 4);
insert into Artist (idArtist, name, idGenre) values (47, 'Hegmann, Weimann and Feeney', 6);
insert into Artist (idArtist, name, idGenre) values (48, 'Langworth-White', 1);
insert into Artist (idArtist, name, idGenre) values (49, 'O''Kon, Reichel and Rohan', 1);
insert into Artist (idArtist, name, idGenre) values (50, 'McDermott, Metz and Bartoletti', 1);
insert into Artist (idArtist, name, idGenre) values (51, 'Denesik Inc', 4);
insert into Artist (idArtist, name, idGenre) values (52, 'Spinka, Hoeger and Lemke', 6);
insert into Artist (idArtist, name, idGenre) values (53, 'Nolan-Beier', 7);
insert into Artist (idArtist, name, idGenre) values (54, 'Runolfsson LLC', 5);
insert into Artist (idArtist, name, idGenre) values (55, 'Beier, Stanton and Erdman', 5);
insert into Artist (idArtist, name, idGenre) values (56, 'Bechtelar and Sons', 3);
insert into Artist (idArtist, name, idGenre) values (57, 'Olson-Crona', 4);
insert into Artist (idArtist, name, idGenre) values (58, 'Bergnaum-Barton', 4);
insert into Artist (idArtist, name, idGenre) values (59, 'Torphy and Sons', 6);
insert into Artist (idArtist, name, idGenre) values (60, 'Schroeder LLC', 5);
insert into Artist (idArtist, name, idGenre) values (61, 'Hand-Kub', 5);
insert into Artist (idArtist, name, idGenre) values (62, 'Shanahan, Hessel and Thiel', 7);
insert into Artist (idArtist, name, idGenre) values (63, 'Gutmann, Dietrich and Wolff', 3);
insert into Artist (idArtist, name, idGenre) values (64, 'Stoltenberg, Weissnat and Blick', 2);
insert into Artist (idArtist, name, idGenre) values (65, 'Goldner-Casper', 1);
insert into Artist (idArtist, name, idGenre) values (66, 'Leannon-Tremblay', 7);
insert into Artist (idArtist, name, idGenre) values (67, 'Monahan, Auer and Walter', 7);
insert into Artist (idArtist, name, idGenre) values (68, 'Altenwerth, Brekke and Denesik', 4);
insert into Artist (idArtist, name, idGenre) values (69, 'Yost Inc', 6);
insert into Artist (idArtist, name, idGenre) values (70, 'Heaney LLC', 3);
insert into Artist (idArtist, name, idGenre) values (71, 'Altenwerth LLC', 1);
insert into Artist (idArtist, name, idGenre) values (72, 'Jacobs, Ernser and Larson', 6);
insert into Artist (idArtist, name, idGenre) values (73, 'Jenkins-Reichert', 8);
insert into Artist (idArtist, name, idGenre) values (74, 'Torphy, Wiza and Yundt', 6);
insert into Artist (idArtist, name, idGenre) values (75, 'Schamberger-Reichel', 2);
insert into Artist (idArtist, name, idGenre) values (76, 'Mueller-Tremblay', 1);
insert into Artist (idArtist, name, idGenre) values (77, 'Luettgen LLC', 2);
insert into Artist (idArtist, name, idGenre) values (78, 'Willms Group', 4);
insert into Artist (idArtist, name, idGenre) values (79, 'Walker, Thiel and Welch', 4);
insert into Artist (idArtist, name, idGenre) values (80, 'Kulas-Gutkowski', 8);
insert into Artist (idArtist, name, idGenre) values (81, 'Grant, Will and Corkery', 7);
insert into Artist (idArtist, name, idGenre) values (82, 'Feest, Monahan and Kuhic', 4);
insert into Artist (idArtist, name, idGenre) values (83, 'Hackett, Heathcote and Jones', 6);
insert into Artist (idArtist, name, idGenre) values (84, 'Padberg, Wuckert and Vandervort', 3);
insert into Artist (idArtist, name, idGenre) values (85, 'Hamill, Zulauf and Macejkovic', 4);
insert into Artist (idArtist, name, idGenre) values (86, 'Skiles, Conroy and Weber', 1);
insert into Artist (idArtist, name, idGenre) values (87, 'Legros and Sons', 1);
insert into Artist (idArtist, name, idGenre) values (88, 'Bins-Hirthe', 3);
insert into Artist (idArtist, name, idGenre) values (89, 'Harris, Johns and Bogan', 1);
insert into Artist (idArtist, name, idGenre) values (90, 'Nader, Abshire and Reichel', 1);
insert into Artist (idArtist, name, idGenre) values (91, 'Mitchell-Streich', 7);
insert into Artist (idArtist, name, idGenre) values (92, 'Greenholt, Casper and Kozey', 2);
insert into Artist (idArtist, name, idGenre) values (93, 'Dooley and Sons', 8);
insert into Artist (idArtist, name, idGenre) values (94, 'Beatty-Osinski', 2);
insert into Artist (idArtist, name, idGenre) values (95, 'Skiles-Abernathy', 5);
insert into Artist (idArtist, name, idGenre) values (96, 'Bosco, Ward and Schmitt', 4);
insert into Artist (idArtist, name, idGenre) values (97, 'Botsford LLC', 3);
insert into Artist (idArtist, name, idGenre) values (98, 'Ryan LLC', 1);
insert into Artist (idArtist, name, idGenre) values (99, 'Pfeffer-Fritsch', 5);
insert into Artist (idArtist, name, idGenre) values (100, 'McCullough and Sons', 5);
